name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: iwamot/workflows/.github/workflows/ci.yml@b292dc0f0ff30f059a866ea6e72acbc9245952ab # v0.10.1
