name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: iwamot/workflows/.github/workflows/ci.yml@b3d2f10167c0cb280d7307b4cbc3dfff42e11c7b # v0.10.5
