name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: iwamot/workflows/.github/workflows/dependabot-auto-merge.yml@abf3e55832d6cc6312c9375a786b13e4021d7007 # v0.5.0
